CREATE TABLE IF NOT EXISTS stweekly.stim_select_outcome_summary (
    summary_key VARCHAR(191) NOT NULL,
    signal_id VARCHAR(64) NOT NULL,
    exchange VARCHAR(8) NULL,
    limit_rank INT NULL,
    start_date DATE NOT NULL,
    end_date DATE NOT NULL,
    generated_at DATETIME NOT NULL,
    source_latest_mature_weekdate DATE NULL,
    `count` BIGINT NOT NULL DEFAULT 0,
    first_weekdate DATE NULL,
    latest_weekdate DATE NULL,
    average_fpr_chg4 DECIMAL(18, 6) NULL,
    median_fpr_chg4 DECIMAL(18, 6) NULL,
    positive_return_count_4wk BIGINT NOT NULL DEFAULT 0,
    positive_return_rate_4wk DECIMAL(18, 10) NOT NULL DEFAULT 0,
    outperform_base_count_4wk BIGINT NOT NULL DEFAULT 0,
    outperform_base_rate_4wk DECIMAL(18, 10) NOT NULL DEFAULT 0,
    average_fpr_chg13 DECIMAL(18, 6) NULL,
    median_fpr_chg13 DECIMAL(18, 6) NULL,
    positive_return_count_13wk BIGINT NOT NULL DEFAULT 0,
    positive_return_rate_13wk DECIMAL(18, 10) NOT NULL DEFAULT 0,
    outperform_base_count_13wk BIGINT NOT NULL DEFAULT 0,
    outperform_base_rate_13wk DECIMAL(18, 10) NOT NULL DEFAULT 0,
    average_fpr_chg40 DECIMAL(18, 6) NULL,
    median_fpr_chg40 DECIMAL(18, 6) NULL,
    positive_return_count_40wk BIGINT NOT NULL DEFAULT 0,
    positive_return_rate_40wk DECIMAL(18, 10) NOT NULL DEFAULT 0,
    outperform_base_count_40wk BIGINT NOT NULL DEFAULT 0,
    outperform_base_rate_40wk DECIMAL(18, 10) NOT NULL DEFAULT 0,
    base_period_mean_4wk DECIMAL(10, 4) NOT NULL,
    base_period_mean_13wk DECIMAL(10, 4) NOT NULL,
    base_period_mean_40wk DECIMAL(10, 4) NOT NULL,
    PRIMARY KEY (summary_key),
    KEY idx_stim_select_outcome_summary_lookup (
        signal_id,
        exchange,
        limit_rank
    ),
    KEY idx_stim_select_outcome_summary_generated_at (generated_at)
);
